logging:
  level:
    root: DEBUG
    fox.FoxFontBuilder: INFO
    sun.rmi: INFO
    sun.awt: INFO
    sun.net.www.protocol.http: INFO
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariDataSource: WARN
    com.codeborne.selenide.impl.CiReportUrl: INFO
    javax.swing: INFO
    javax.management.remote.rmi: INFO
    java.awt.mixing: INFO
    java.awt.event.WaitDispatchSupport: INFO
    java.awt.focus.DefaultKeyboardFocusManager: INFO
    jdk.event.security: INFO
    org.hibernate: WARN
    org.hibernate.Version: INFO
    org.hibernate.annotations.common.Version: WARN
    org.jboss.logging: INFO
    org.apache: INFO
    org.springframework.ui: INFO
    org.springframework.jmx: INFO
    org.springframework.orm: WARN
    org.springframework.boot: WARN
    org.springframework.context: INFO
    org.springframework.core: INFO
    org.springframework.scheduling: INFO
    org.springframework.web: INFO
    org.springframework.aop: INFO
    org.springframework.beans: INFO
    org.springframework.data: INFO
    org.springframework.validation.beanvalidation: INFO
    org.springframework.statemachine.support.LifecycleObjectSupport: INFO
    org.springframework.jdbc.datasource.DataSourceUtils: INFO
    org.asynchttpclient.netty: INFO
    org.openqa.selenium: INFO
    com.codeborne.selenide: WARN
    io.netty: INFO
    io.micrometer.core.util: INFO

server:
  port: 8082
  error:
    whitelabel:
      # false - для отображения фактического ответа сервера, вместо белой страницы с описанием:
      enabled: false

spring:
  main:
    allow-circular-references: false
    lazy-initialization: false
    allow-bean-definition-overriding: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:invest}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          # Hibernate прозрачно отключает пакетную вставку на уровне JDBC, если вы используете генератор IDENTITY
          batch_size: 10
          batch_versioned_data: true
        order_updates: true
        auto_quote_keyword: true
        globally_quoted_identifiers: true
        connection:
          # autocommit: true // не рекомендуется
          pool_size: 10

app:
  sites:
    count: ${APP_SITES_COUNT:6}

  selenide:
    test_timeout: ${SELENIDE_TEST_TIMEOUT:15000}
    page_load_timeout: ${SELENIDE_PAGE_LOAD_TIMEOUT:9000}
    polling_interval: ${SELENIDE_POLL_INTERVAL:200}
    # remote_read_timeout: ${SELENIDE_RREAD_TIMEOUT:30_000}
    # remote_connect_timeout: ${SELENIDE_RCONN_TIMEOUT:30_000}

    max_error_count: 30
    each_state_sleep: 5_000
    tab_click_sleep: 5_000
    purchases_shift_sleep: 5_000
    technical_work_sleep: 360_000
    max_depth_sleep: 360_000
