package ru.investment.parser.enums;

public enum ParserEvents {
    ON_SETUP_STARTED,
    ON_SETUP_COMPLETED,
    ON_SEARCHING_DATA,
    ON_NEW_DATA_FOUND,
    ON_PARSING_DATA,
    ON_PARSED_SUCCESSFULLY,
    ON_DATA_SAVED,
    ON_DATA_NOT_FOUND,
    ON_BROKEN_PAGE_FOUND,
    ON_ERROR_OCCURRED,
    ON_ERROR_COUNT_NOT_EXCEEDED,
    ON_ERROR_COUNT_EXCEEDED,
    ON_STOP_BY_USER,
    ON_TECHNICAL_WORK,
    ON_MAX_TRIES_REACHED,
    ON_ACCOMPLISHED
}
